# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/elijah/Desktop/diss

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/elijah/Desktop/diss

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/elijah/Desktop/diss/CMakeFiles /Users/elijah/Desktop/diss//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/elijah/Desktop/diss/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hashing_algos

# Build rule for target.
hashing_algos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hashing_algos
.PHONY : hashing_algos

# fast build rule for target.
hashing_algos/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/build
.PHONY : hashing_algos/fast

src/algos/recsplit.o: src/algos/recsplit.cpp.o
.PHONY : src/algos/recsplit.o

# target to build an object file
src/algos/recsplit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/algos/recsplit.cpp.o
.PHONY : src/algos/recsplit.cpp.o

src/algos/recsplit.i: src/algos/recsplit.cpp.i
.PHONY : src/algos/recsplit.i

# target to preprocess a source file
src/algos/recsplit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/algos/recsplit.cpp.i
.PHONY : src/algos/recsplit.cpp.i

src/algos/recsplit.s: src/algos/recsplit.cpp.s
.PHONY : src/algos/recsplit.s

# target to generate assembly for a file
src/algos/recsplit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/algos/recsplit.cpp.s
.PHONY : src/algos/recsplit.cpp.s

src/common/golomb_rice.o: src/common/golomb_rice.cpp.o
.PHONY : src/common/golomb_rice.o

# target to build an object file
src/common/golomb_rice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/golomb_rice.cpp.o
.PHONY : src/common/golomb_rice.cpp.o

src/common/golomb_rice.i: src/common/golomb_rice.cpp.i
.PHONY : src/common/golomb_rice.i

# target to preprocess a source file
src/common/golomb_rice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/golomb_rice.cpp.i
.PHONY : src/common/golomb_rice.cpp.i

src/common/golomb_rice.s: src/common/golomb_rice.cpp.s
.PHONY : src/common/golomb_rice.s

# target to generate assembly for a file
src/common/golomb_rice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/golomb_rice.cpp.s
.PHONY : src/common/golomb_rice.cpp.s

src/common/murmurhash.o: src/common/murmurhash.cpp.o
.PHONY : src/common/murmurhash.o

# target to build an object file
src/common/murmurhash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/murmurhash.cpp.o
.PHONY : src/common/murmurhash.cpp.o

src/common/murmurhash.i: src/common/murmurhash.cpp.i
.PHONY : src/common/murmurhash.i

# target to preprocess a source file
src/common/murmurhash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/murmurhash.cpp.i
.PHONY : src/common/murmurhash.cpp.i

src/common/murmurhash.s: src/common/murmurhash.cpp.s
.PHONY : src/common/murmurhash.s

# target to generate assembly for a file
src/common/murmurhash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/murmurhash.cpp.s
.PHONY : src/common/murmurhash.cpp.s

src/common/utils.o: src/common/utils.cpp.o
.PHONY : src/common/utils.o

# target to build an object file
src/common/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/utils.cpp.o
.PHONY : src/common/utils.cpp.o

src/common/utils.i: src/common/utils.cpp.i
.PHONY : src/common/utils.i

# target to preprocess a source file
src/common/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/utils.cpp.i
.PHONY : src/common/utils.cpp.i

src/common/utils.s: src/common/utils.cpp.s
.PHONY : src/common/utils.s

# target to generate assembly for a file
src/common/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/utils.cpp.s
.PHONY : src/common/utils.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hashing_algos"
	@echo "... src/algos/recsplit.o"
	@echo "... src/algos/recsplit.i"
	@echo "... src/algos/recsplit.s"
	@echo "... src/common/golomb_rice.o"
	@echo "... src/common/golomb_rice.i"
	@echo "... src/common/golomb_rice.s"
	@echo "... src/common/murmurhash.o"
	@echo "... src/common/murmurhash.i"
	@echo "... src/common/murmurhash.s"
	@echo "... src/common/utils.o"
	@echo "... src/common/utils.i"
	@echo "... src/common/utils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

