# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/elijah/Desktop/diss

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/elijah/Desktop/diss

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/elijah/Desktop/diss/CMakeFiles /Users/elijah/Desktop/diss//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/elijah/Desktop/diss/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hashing_algos

# Build rule for target.
hashing_algos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hashing_algos
.PHONY : hashing_algos

# fast build rule for target.
hashing_algos/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/build
.PHONY : hashing_algos/fast

#=============================================================================
# Target rules for targets named common_lib

# Build rule for target.
common_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common_lib
.PHONY : common_lib

# fast build rule for target.
common_lib/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/common_lib.dir/build.make tests/CMakeFiles/common_lib.dir/build
.PHONY : common_lib/fast

#=============================================================================
# Target rules for targets named test_elias_fano

# Build rule for target.
test_elias_fano: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_elias_fano
.PHONY : test_elias_fano

# fast build rule for target.
test_elias_fano/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_elias_fano.dir/build.make tests/CMakeFiles/test_elias_fano.dir/build
.PHONY : test_elias_fano/fast

#=============================================================================
# Target rules for targets named run_test_elias_fano

# Build rule for target.
run_test_elias_fano: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_test_elias_fano
.PHONY : run_test_elias_fano

# fast build rule for target.
run_test_elias_fano/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_test_elias_fano.dir/build.make tests/CMakeFiles/run_test_elias_fano.dir/build
.PHONY : run_test_elias_fano/fast

#=============================================================================
# Target rules for targets named test_golomb_rice

# Build rule for target.
test_golomb_rice: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_golomb_rice
.PHONY : test_golomb_rice

# fast build rule for target.
test_golomb_rice/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_golomb_rice.dir/build.make tests/CMakeFiles/test_golomb_rice.dir/build
.PHONY : test_golomb_rice/fast

#=============================================================================
# Target rules for targets named run_golomb_rice

# Build rule for target.
run_golomb_rice: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_golomb_rice
.PHONY : run_golomb_rice

# fast build rule for target.
run_golomb_rice/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_golomb_rice.dir/build.make tests/CMakeFiles/run_golomb_rice.dir/build
.PHONY : run_golomb_rice/fast

#=============================================================================
# Target rules for targets named run_all_tests

# Build rule for target.
run_all_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_all_tests
.PHONY : run_all_tests

# fast build rule for target.
run_all_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/run_all_tests.dir/build.make tests/CMakeFiles/run_all_tests.dir/build
.PHONY : run_all_tests/fast

src/algos/recsplit.o: src/algos/recsplit.cpp.o
.PHONY : src/algos/recsplit.o

# target to build an object file
src/algos/recsplit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/algos/recsplit.cpp.o
.PHONY : src/algos/recsplit.cpp.o

src/algos/recsplit.i: src/algos/recsplit.cpp.i
.PHONY : src/algos/recsplit.i

# target to preprocess a source file
src/algos/recsplit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/algos/recsplit.cpp.i
.PHONY : src/algos/recsplit.cpp.i

src/algos/recsplit.s: src/algos/recsplit.cpp.s
.PHONY : src/algos/recsplit.s

# target to generate assembly for a file
src/algos/recsplit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/algos/recsplit.cpp.s
.PHONY : src/algos/recsplit.cpp.s

src/algos/sichash.o: src/algos/sichash.cpp.o
.PHONY : src/algos/sichash.o

# target to build an object file
src/algos/sichash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/algos/sichash.cpp.o
.PHONY : src/algos/sichash.cpp.o

src/algos/sichash.i: src/algos/sichash.cpp.i
.PHONY : src/algos/sichash.i

# target to preprocess a source file
src/algos/sichash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/algos/sichash.cpp.i
.PHONY : src/algos/sichash.cpp.i

src/algos/sichash.s: src/algos/sichash.cpp.s
.PHONY : src/algos/sichash.s

# target to generate assembly for a file
src/algos/sichash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/algos/sichash.cpp.s
.PHONY : src/algos/sichash.cpp.s

src/common/elias_fano.o: src/common/elias_fano.cpp.o
.PHONY : src/common/elias_fano.o

# target to build an object file
src/common/elias_fano.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/elias_fano.cpp.o
.PHONY : src/common/elias_fano.cpp.o

src/common/elias_fano.i: src/common/elias_fano.cpp.i
.PHONY : src/common/elias_fano.i

# target to preprocess a source file
src/common/elias_fano.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/elias_fano.cpp.i
.PHONY : src/common/elias_fano.cpp.i

src/common/elias_fano.s: src/common/elias_fano.cpp.s
.PHONY : src/common/elias_fano.s

# target to generate assembly for a file
src/common/elias_fano.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/elias_fano.cpp.s
.PHONY : src/common/elias_fano.cpp.s

src/common/golomb_rice.o: src/common/golomb_rice.cpp.o
.PHONY : src/common/golomb_rice.o

# target to build an object file
src/common/golomb_rice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/golomb_rice.cpp.o
.PHONY : src/common/golomb_rice.cpp.o

src/common/golomb_rice.i: src/common/golomb_rice.cpp.i
.PHONY : src/common/golomb_rice.i

# target to preprocess a source file
src/common/golomb_rice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/golomb_rice.cpp.i
.PHONY : src/common/golomb_rice.cpp.i

src/common/golomb_rice.s: src/common/golomb_rice.cpp.s
.PHONY : src/common/golomb_rice.s

# target to generate assembly for a file
src/common/golomb_rice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/golomb_rice.cpp.s
.PHONY : src/common/golomb_rice.cpp.s

src/common/murmurhash.o: src/common/murmurhash.cpp.o
.PHONY : src/common/murmurhash.o

# target to build an object file
src/common/murmurhash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/murmurhash.cpp.o
.PHONY : src/common/murmurhash.cpp.o

src/common/murmurhash.i: src/common/murmurhash.cpp.i
.PHONY : src/common/murmurhash.i

# target to preprocess a source file
src/common/murmurhash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/murmurhash.cpp.i
.PHONY : src/common/murmurhash.cpp.i

src/common/murmurhash.s: src/common/murmurhash.cpp.s
.PHONY : src/common/murmurhash.s

# target to generate assembly for a file
src/common/murmurhash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/murmurhash.cpp.s
.PHONY : src/common/murmurhash.cpp.s

src/common/utils.o: src/common/utils.cpp.o
.PHONY : src/common/utils.o

# target to build an object file
src/common/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/utils.cpp.o
.PHONY : src/common/utils.cpp.o

src/common/utils.i: src/common/utils.cpp.i
.PHONY : src/common/utils.i

# target to preprocess a source file
src/common/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/utils.cpp.i
.PHONY : src/common/utils.cpp.i

src/common/utils.s: src/common/utils.cpp.s
.PHONY : src/common/utils.s

# target to generate assembly for a file
src/common/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/common/utils.cpp.s
.PHONY : src/common/utils.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hashing_algos.dir/build.make CMakeFiles/hashing_algos.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... run_all_tests"
	@echo "... run_golomb_rice"
	@echo "... run_test_elias_fano"
	@echo "... common_lib"
	@echo "... hashing_algos"
	@echo "... test_elias_fano"
	@echo "... test_golomb_rice"
	@echo "... src/algos/recsplit.o"
	@echo "... src/algos/recsplit.i"
	@echo "... src/algos/recsplit.s"
	@echo "... src/algos/sichash.o"
	@echo "... src/algos/sichash.i"
	@echo "... src/algos/sichash.s"
	@echo "... src/common/elias_fano.o"
	@echo "... src/common/elias_fano.i"
	@echo "... src/common/elias_fano.s"
	@echo "... src/common/golomb_rice.o"
	@echo "... src/common/golomb_rice.i"
	@echo "... src/common/golomb_rice.s"
	@echo "... src/common/murmurhash.o"
	@echo "... src/common/murmurhash.i"
	@echo "... src/common/murmurhash.s"
	@echo "... src/common/utils.o"
	@echo "... src/common/utils.i"
	@echo "... src/common/utils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

